### ISSUE TITLE
Code triple segfaults

### ISSUE THREAD

**Issue by nachatz** [msi1995/Me#2]
- **### **Helo, I notice when i run the code it says triple SegFault. I believe the error said I needed node.json? where is ndoe.json? documentation plz?****

**Comment by nachatz** [comment]
documentacion* sirry spoelinng

**Comment by msi1995** [comment]
![maxresdefault (4)](https://user-images.githubusercontent.com/63132397/163843021-b628e455-78be-4bd1-945c-ba2296a22da0.jpg)
